import type { PosterForm, PosterState } from "@/context/posterReducer";
import { getTheme, defaultThemeName } from "@/services/theme/themeRepository";
import { createDefaultMarkerSettings } from "@/services/markers/helpers";
import { createDefaultRouteSettings } from "@/services/routes/helpers";
import { defaultLayoutId, getLayoutOption } from "@/services/layout/layoutRepository";
import {
  DEFAULT_POSTER_WIDTH_CM,
  DEFAULT_POSTER_HEIGHT_CM,
  DEFAULT_DISTANCE_METERS,
  DEFAULT_LAT,
  DEFAULT_LON,
} from "@/services/config";

const defaultLayout = getLayoutOption(defaultLayoutId);

const DEFAULT_FORM: PosterForm = {
  location: "Phnom Penh, Cambodia",
  latitude: DEFAULT_LAT.toFixed(6),
  longitude: DEFAULT_LON.toFixed(6),
  distance: String(DEFAULT_DISTANCE_METERS),
  width: String(Number(defaultLayout?.widthCm ?? DEFAULT_POSTER_WIDTH_CM)),
  height: String(Number(defaultLayout?.heightCm ?? DEFAULT_POSTER_HEIGHT_CM)),
  theme: defaultThemeName,
  theme2: defaultThemeName,
  layout: defaultLayoutId,
  displayCity: "Phnom Penh",
  displayCountry: "Cambodia",
  displayContinent: "Asia",
  footerCity: "Phnom Penh",
  footerCountry: "Cambodia",
  fontFamily: "Bebas Neue",
  showPosterText: true,
  includeCredits: true,
  includeLandcover: true,
  includeBuildings: true,
  includeWater: true,
  includeParks: true,
  includeAeroway: true,
  includeRail: true,
  includeRoads: true,
  includeRoadPath: true,
  includeRoadMinorLow: true,
  includeRoadOutline: true,
  tileProvider: "openfreemap",
  mapShape: "rectangle",
  footerStyle: "solid",
  showBorder: true,
  showCoordinates: true,
  showUnderline: true,
  titleAllCaps: false,
  showMarkers: true,
  showRoutes: true,
  showQrCode: false,
  qrDestination: "google-maps",
  qrCustomUrl: "",
  qrPosition: "bottom-right",
  logoUrl: "",
  logoPosition: "top-right",
  radiusMeters: "0",
  showPois: false,
  appTheme: "dark",
  uiDensity: "comfortable",
  qrSize: "12",
  qrOpacity: "100",
  qrPadding: "6",
  logoSize: "25",
  logoOpacity: "100",
  logoPadding: "0",
  qrPhone: "",
  qrX: "92",
  qrY: "92",
  logoX: "92",
  logoY: "10",
  qrLabel: "",
  letterSpacing: "0",
  titleAlign: "center",
  coordsFormat: "decimal",
  layoutMode: "poster",
  location2: "Paris, France",
  latitude2: "48.8566",
  longitude2: "2.3522",
  distance2: String(DEFAULT_DISTANCE_METERS),
  displayCity2: "Paris",
  displayCountry2: "France",
  displayContinent2: "Europe",
  propType: "Villa",
  propPrice: "$185,000",
  propLandSize: "200m²",
  propBuildSize: "150m²",
  propContact: "+855 12 345 678",
  propAgent: "Agent Name",
  propCta: "Call Now",
  propFeatures: "3 Bed • 2 Bath • Pool",
  propStatus: "For Sale",
  propBedrooms: "3",
  propBathrooms: "2",
  propWebsite: "",
  propAgentLogo: "",
  shopOpen: "7AM – 8PM daily",
  shopTagline: "Your neighborhood store",
  shopInstagram: "",
  shopFacebook: "",
  shopTelegram: "",
  shopWhatsapp: "",
  shopPhone: "+855 12 345 678",
  snapToRoads: true,
  poiSchools: false,
  poiHospitals: false,
  poiMarkets: false,
  poiBanks: false,
  poiRestaurants: false,
  focusCountry: false,
  radiusLabel: "5 min walk",
  radiusStyle: "dashed",
};

const defaultTheme = getTheme(defaultThemeName);
export const INITIAL_STATE: PosterState = {
  form: DEFAULT_FORM,
  customColors: {},
  markers: [],
  customMarkerIcons: [],
  markerDefaults: { ...createDefaultMarkerSettings(), color: defaultTheme.ui.text },
  isMarkerEditorActive: false,
  routeDrawMode: false,
  routeEditMode: false,
  activeMarkerId: null,
  routes: [],
  routeDefaults: { ...createDefaultRouteSettings(), color: defaultTheme.ui.text },
  error: "",
  isExporting: false,
  isLocationFocused: false,
  selectedLocation: null,
  userLocation: null,
  displayNameOverrides: { city: false, country: false },
};
